[package]
name = "valence-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9.0"
tokio = "1.43.0"
uuid = { version = "1.11.0", features = ["v4"] }
valence = { path = "../valence" }
