[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip=esp32c6"
#runner = "espflash flash --monitor"

[env]
DEFMT_LOG="info"

[build]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
